## Single mask palette changer

In [9]:
import cv2
import numpy as np
from PIL import Image

palette = [
    [128, 0, 0],
    [0, 128, 0],
    [128, 128, 0],
    [0, 0, 128],
    [128, 0, 128],
    [0, 128, 128],
    [128, 128, 128],
    [64, 0, 0]
]

img = cv2.imread('/kaggle/input/beach-litter-dataset/test_masks/002800.png')
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
h, w = img.shape[:2]
print(img)

img_pal = np.zeros((h, w), np.uint8)
for i_p, p in enumerate(palette):
    img_pal[np.all(img == p, axis=2)] = i_p
cv2.imwrite('output.png', img_pal)

# img_pil = Image.open('output.png')
# print(np.array(img_pil))

[[[  0 128 128]
  [  0 128 128]
  [  0 128 128]
  ...
  [  0 128 128]
  [  0 128 128]
  [  0 128 128]]

 [[  0 128 128]
  [  0 128 128]
  [  0 128 128]
  ...
  [  0 128 128]
  [  0 128 128]
  [  0 128 128]]

 [[  0 128 128]
  [  0 128 128]
  [  0 128 128]
  ...
  [  0 128 128]
  [  0 128 128]
  [  0 128 128]]

 ...

 [[128 128 128]
  [128 128 128]
  [128 128 128]
  ...
  [128 128 128]
  [128 128 128]
  [128 128 128]]

 [[128 128 128]
  [128 128 128]
  [128 128 128]
  ...
  [128 128 128]
  [128 128 128]
  [128 128 128]]

 [[128 128 128]
  [128 128 128]
  [128 128 128]
  ...
  [128 128 128]
  [128 128 128]
  [128 128 128]]]
[[5 5 5 ... 5 5 5]
 [5 5 5 ... 5 5 5]
 [5 5 5 ... 5 5 5]
 ...
 [6 6 6 ... 6 6 6]
 [6 6 6 ... 6 6 6]
 [6 6 6 ... 6 6 6]]


In [10]:
# img = cv2.imread('/kaggle/input/beach-litter-dataset/test_masks/002800.png')
# img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
# # print(np.unique(img))
# set( tuple(v) for m2d in img for v in m2d )

{(0, 0, 128), (0, 128, 128), (128, 0, 128), (128, 128, 128)}

In [11]:
# img = cv2.imread('/kaggle/input/beach-litter-dataset/test_masks/002857.png')
# img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
# # print(np.unique(img))
# set( tuple(v) for m2d in img for v in m2d )

{(0, 0, 128),
 (0, 128, 0),
 (0, 128, 128),
 (64, 0, 0),
 (128, 0, 0),
 (128, 0, 128),
 (128, 128, 0),
 (128, 128, 128)}

## Multiple masks palette changer

In [1]:
# https://stackoverflow.com/questions/67967366/how-to-write-image-with-palette-information

import cv2
import numpy as np
from PIL import Image
import os

palette = [
    [128, 0, 0],
    [0, 128, 0],
    [128, 128, 0],
    [0, 0, 128],
    [128, 0, 128],
    [0, 128, 128],
    [128, 128, 128],
    [64, 0, 0]
]
mask_list = os.listdir('/kaggle/input/beach-litter-dataset/test_masks')

folder_path = "/kaggle/working/output_images"
os.makedirs(folder_path, exist_ok = True)

for i in mask_list:
    img_path = os.path.join('/kaggle/input/beach-litter-dataset/test_masks', i)
    img = cv2.imread(img_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    h, w = img.shape[:2]

    img_pal = np.zeros((h, w), np.uint8)
    for i_p, p in enumerate(palette):
        img_pal[np.all(img == p, axis=2)] = i_p
    output_path = os.path.join(folder_path, i)
    cv2.imwrite(output_path, img_pal)

## Multiple masks palette changer with custom class indexing

In [1]:
# https://stackoverflow.com/questions/67967366/how-to-write-image-with-palette-information

import cv2
import numpy as np
from PIL import Image
import os

palette = [
    [128, 0, 0],
    [0, 128, 0],
    [128, 128, 0],
    [0, 0, 128],
    [128, 0, 128],
    [0, 128, 128],
    [128, 128, 128],
    [64, 0, 0]
]

custom_idx = [1, 0, 0, 0, 2, 0, 0, 0]

mask_list = os.listdir('/kaggle/input/beach-litter-dataset/Beachlitter_prepped/train_masks')

folder_path = "/kaggle/working/output_images"
os.makedirs(folder_path, exist_ok = True)

for i in mask_list:
    img_path = os.path.join('/kaggle/input/beach-litter-dataset/Beachlitter_prepped/train_masks', i)
    img = cv2.imread(img_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    h, w = img.shape[:2]

    img_pal = np.zeros((h, w), np.uint8)
    for i_p, p in zip(custom_idx, palette):
        img_pal[np.all(img == p, axis=2)] = i_p
    output_path = os.path.join(folder_path, i)
    cv2.imwrite(output_path, img_pal)

In [1]:
from PIL import Image
img_pil = Image.open('/kaggle/input/beach-litter-dataset/Beachlitter_masks_litter_only/train_litter_mask/000857.png')
img_pil = img_pil.convert('P')
palette = [
    0, 0, 0,
    128, 0, 0,
    0, 128, 0]
img_pil.putpalette(palette)
img_pil.save('output_indexed.png')

## zip output folder

In [3]:
import shutil

# # Path to the folder you want to compress
# folder_path = '/kaggle/working/output_images'

# Path where you want to save the compressed file
zip_path = '/kaggle/working/output_images.zip'

# Compress the folder
shutil.make_archive(zip_path.replace('.zip', ''), 'zip', folder_path)

'/kaggle/working/output_images.zip'

In [ ]:
# mask_list